In [1]:
import numpy as np
import pandas as pd
import pickle
import joblib
import matplotlib.pyplot as plt
from numpy import loadtxt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from tqdm import tqdm
from xgboost import plot_importance
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd


In [6]:
# Import the dataset
df = pd.concat(map(pd.read_csv, ['metasploitable-2.csv','Normal_data.csv']), ignore_index=True)
df["Src IP"] = [float(str(i).replace(".", "")) for i in df["Src IP"]]
df["Dst IP"] = [float(str(i).replace(".", "")) for i in df["Dst IP"]]
df["Flow ID"] = [float(str(i).replace(".", "").replace("-", "")) for i in df["Flow ID"]]
df["Timestamp"] = [float(str(i).replace("/", "").replace(":", "").replace(" ","").replace("PM","")) for i in df["Timestamp"]]
print(df)

             Flow ID        Src IP  Src Port        Dst IP  Dst Port  \
0       1.921683e+29  1.921683e+09     38694  2.001752e+09      4444   
1       1.921683e+29  1.921683e+09     38693  2.001752e+09      4444   
2       1.921683e+29  2.001752e+09     33747  1.921683e+09      3632   
3       1.921683e+29  2.001752e+09     38745  1.921683e+09      8180   
4       1.921683e+29  2.001752e+09     37217  1.921683e+09      8180   
...              ...           ...       ...           ...       ...   
205162  1.851272e+29  1.921682e+10     36100  1.851272e+09       443   
205163  1.921682e+28  1.921682e+10     53032  1.921682e+08        53   
205164  1.921682e+28  1.921682e+10     39285  1.921682e+08        53   
205165  1.921682e+28  1.921682e+10     49895  1.921682e+08        53   
205166  1.921682e+28  1.921682e+10     33786  1.921682e+08        53   

        Protocol     Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  \
0              6  1.012021e+09         269709             

In [7]:
# Splitting dataset into features and label
X = df.drop('Label', axis=1)
y = df['Label']

In [10]:
# Splitting the dataset into the training set and the test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [11]:
# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
# Fitting SVM with the training set
SVM = SVC(kernel='linear', random_state=0)
SVM.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [16]:
# Testing the model by classifying the test set
y_pred = SVM.predict(X_test)

In [17]:
# Creating confusion matrix for evaluation
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from xgboost import plot_importance
from numpy import loadtxt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
import pickle
from tqdm import tqdm
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import recall_score
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler

In [19]:
#run this if you want to upload the dataset from your google drive
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [20]:
train= pd.concat(map(pd.read_csv, ['metasploitable-2.csv', 'Normal_data.csv']))
train["Src IP"] = [float(str(i).replace(".", "")) for i in train["Src IP"]]
train["Dst IP"] = [float(str(i).replace(".", "")) for i in train["Dst IP"]]
train["Flow ID"] = [float(str(i).replace(".", "").replace("-", "")) for i in train["Flow ID"]]
train["Timestamp"] = [float(str(i).replace("/", "").replace(":", "").replace(" ","").replace("PM","")) for i in train["Timestamp"]]
print(train)


            Flow ID        Src IP  Src Port        Dst IP  Dst Port  Protocol  \
0      1.921683e+29  1.921683e+09     38694  2.001752e+09      4444         6   
1      1.921683e+29  1.921683e+09     38693  2.001752e+09      4444         6   
2      1.921683e+29  2.001752e+09     33747  1.921683e+09      3632         6   
3      1.921683e+29  2.001752e+09     38745  1.921683e+09      8180         6   
4      1.921683e+29  2.001752e+09     37217  1.921683e+09      8180         6   
...             ...           ...       ...           ...       ...       ...   
68419  1.851272e+29  1.921682e+10     36100  1.851272e+09       443         6   
68420  1.921682e+28  1.921682e+10     53032  1.921682e+08        53        17   
68421  1.921682e+28  1.921682e+10     39285  1.921682e+08        53        17   
68422  1.921682e+28  1.921682e+10     49895  1.921682e+08        53        17   
68423  1.921682e+28  1.921682e+10     33786  1.921682e+08        53        17   

          Timestamp  Flow D

In [21]:
from sklearn import preprocessing
for f in train.columns:
  if train[f].dtype=='object':
    label = preprocessing.LabelEncoder()
    label.fit(list(train[f].values))
    train[f] = label.transform(list(train[f].values))
train.fillna((-999), inplace=True)
train=np.array(train)
train = train.astype(float)

In [22]:
train = pd.DataFrame(train)
print(train)

                  0             1        2             3       4     5   \
0       1.921683e+29  1.921683e+09  38694.0  2.001752e+09  4444.0   6.0   
1       1.921683e+29  1.921683e+09  38693.0  2.001752e+09  4444.0   6.0   
2       1.921683e+29  2.001752e+09  33747.0  1.921683e+09  3632.0   6.0   
3       1.921683e+29  2.001752e+09  38745.0  1.921683e+09  8180.0   6.0   
4       1.921683e+29  2.001752e+09  37217.0  1.921683e+09  8180.0   6.0   
...              ...           ...      ...           ...     ...   ...   
205162  1.851272e+29  1.921682e+10  36100.0  1.851272e+09   443.0   6.0   
205163  1.921682e+28  1.921682e+10  53032.0  1.921682e+08    53.0  17.0   
205164  1.921682e+28  1.921682e+10  39285.0  1.921682e+08    53.0  17.0   
205165  1.921682e+28  1.921682e+10  49895.0  1.921682e+08    53.0  17.0   
205166  1.921682e+28  1.921682e+10  33786.0  1.921682e+08    53.0  17.0   

                  6         7    8    9   ...   74   75   76   77   78   79  \
0       1.012021e+09

In [23]:
X = train.drop(train.columns[[81]], axis=1)
y=train[train.columns[[81]]]

In [24]:
# split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

In [25]:
X_train = StandardScaler().fit_transform(X_train)
X_test = StandardScaler().fit_transform(X_test)

In [26]:
NB=GaussianNB()
NB.fit(X_train, y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [27]:
y_pred = NB.predict(X_test)

In [28]:
accuracy = accuracy_score(y_test, y_pred)
print("accuracy:",accuracy)


accuracy: 0.8401975597472016


In [29]:
f1score=f1_score(y_test, y_pred, average='micro')
print("f1-acore:",f1score)


f1-acore: 0.8401975597472016


In [30]:
cm=confusion_matrix(y_test, y_pred)
print("confusion matrix:",cm)


confusion matrix: [[51676     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]


In [31]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.99      1.00     52045
   5000001.0       0.00      0.00      0.00         1
   5000015.0       0.00      0.00      0.00         1
   5000058.0       0.00      0.00      0.00         1
   5000120.0       0.00      0.00      0.00         1
   5000133.0       0.00      0.00      0.00         1
   5000140.0       0.00      0.00      0.00         1
   5000150.0       0.00      0.00      0.00         1
   5000154.0       0.00      0.00      0.00         1
   5000157.0       0.00      0.00      0.00         1
   5000167.0       0.00      0.00      0.00         1
   5000183.0       0.00      0.00      0.00         1
   5000191.0       0.00      0.00      0.00         1
   5000251.0       0.00      0.00      0.00         1
   5000254.0       0.00      0.00      0.00         1
   5000259.0       0.00      0.00      0.00         1
   5000265.0       0.00      0.00      0.00         1
   5000267.0       0.00    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

In [32]:
pr=precision_score(y_test,y_pred, average='micro')
print("Precision:",pr)

Precision: 0.8401975597472016


# KNN

In [33]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix


In [34]:
#import the dataset
df= pd.concat(map(pd.read_csv, ['metasploitable-2.csv', 'Normal_data.csv']), ignore_index=True)
df["Src IP"] = [float(str(i).replace(".", "")) for i in df["Src IP"]]
df["Dst IP"] = [float(str(i).replace(".", "")) for i in df["Dst IP"]]
df["Flow ID"] = [float(str(i).replace(".", "").replace("-", "")) for i in df["Flow ID"]]
df["Timestamp"] = [float(str(i).replace("/", "").replace(":", "").replace(" ","").replace("PM","")) for i in df["Timestamp"]]

print(df)

             Flow ID        Src IP  Src Port        Dst IP  Dst Port  \
0       1.921683e+29  1.921683e+09     38694  2.001752e+09      4444   
1       1.921683e+29  1.921683e+09     38693  2.001752e+09      4444   
2       1.921683e+29  2.001752e+09     33747  1.921683e+09      3632   
3       1.921683e+29  2.001752e+09     38745  1.921683e+09      8180   
4       1.921683e+29  2.001752e+09     37217  1.921683e+09      8180   
...              ...           ...       ...           ...       ...   
205162  1.851272e+29  1.921682e+10     36100  1.851272e+09       443   
205163  1.921682e+28  1.921682e+10     53032  1.921682e+08        53   
205164  1.921682e+28  1.921682e+10     39285  1.921682e+08        53   
205165  1.921682e+28  1.921682e+10     49895  1.921682e+08        53   
205166  1.921682e+28  1.921682e+10     33786  1.921682e+08        53   

        Protocol     Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  \
0              6  1.012021e+09         269709             

In [36]:
X = df.drop('Label', axis=1)
y = df['Label'].values


In [37]:
#Split the training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)


In [38]:
#feature Scaling
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


In [39]:
#here we train the KNN algorithm to make predictions with it

KNN = KNeighborsClassifier(n_neighbors=5)
KNN.fit(X_train, y_train)

KNeighborsClassifier()

In [40]:
#make predictions on the test data
y_pred = KNN.predict(X_test)

In [41]:
print(confusion_matrix(y_test, y_pred))


[[   54     0     0     0     0     0]
 [    0 14630     0     2     1     0]
 [    0     0   222     0     3     0]
 [    0     2     0 13650     1     0]
 [    0     0     0     0 12464     0]
 [    0     0     0     2     2     1]]


In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         BFA       1.00      1.00      1.00        54
        DDoS       1.00      1.00      1.00     14633
         DoS       1.00      0.99      0.99       225
      Normal       1.00      1.00      1.00     13653
       Probe       1.00      1.00      1.00     12464
         U2R       1.00      0.20      0.33         5

    accuracy                           1.00     41034
   macro avg       1.00      0.86      0.89     41034
weighted avg       1.00      1.00      1.00     41034



# RF

In [43]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [44]:
#import the dataset
df = pd.concat(map(pd.read_csv, ['metasploitable-2.csv', 'Normal_data.csv']), ignore_index=True)
df["Src IP"] = [float(str(i).replace(".", "")) for i in df["Src IP"]]
df["Dst IP"] = [float(str(i).replace(".", "")) for i in df["Dst IP"]]
df["Flow ID"] = [float(str(i).replace(".", "").replace("-", "")) for i in df["Flow ID"]]
df["Timestamp"] = [float(str(i).replace("/", "").replace(":", "").replace(" ","").replace("PM","")) for i in df["Timestamp"]]

print(df)

             Flow ID        Src IP  Src Port        Dst IP  Dst Port  \
0       1.921683e+29  1.921683e+09     38694  2.001752e+09      4444   
1       1.921683e+29  1.921683e+09     38693  2.001752e+09      4444   
2       1.921683e+29  2.001752e+09     33747  1.921683e+09      3632   
3       1.921683e+29  2.001752e+09     38745  1.921683e+09      8180   
4       1.921683e+29  2.001752e+09     37217  1.921683e+09      8180   
...              ...           ...       ...           ...       ...   
205162  1.851272e+29  1.921682e+10     36100  1.851272e+09       443   
205163  1.921682e+28  1.921682e+10     53032  1.921682e+08        53   
205164  1.921682e+28  1.921682e+10     39285  1.921682e+08        53   
205165  1.921682e+28  1.921682e+10     49895  1.921682e+08        53   
205166  1.921682e+28  1.921682e+10     33786  1.921682e+08        53   

        Protocol     Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  \
0              6  1.012021e+09         269709             

In [46]:
#here we are preprocessing
X = df.drop('Label',axis=1)
y = df['Label'].values

In [47]:
# Splitting the dataset into the Training set and Test set
X_Train, X_Test, y_Train, y_Test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [48]:
# Feature Scaling
X_Train = StandardScaler().fit_transform(X_Train)
X_Test = StandardScaler().fit_transform(X_Test)

In [49]:
# Fitting the classifier into the Training set
RF = RandomForestClassifier(n_estimators = 200, criterion = 'entropy', random_state = 0)
RF.fit(X_Train,y_Train)

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)

In [51]:
# Predicting the test set results
y_Pred = RF.predict(X_Test)

In [52]:
# Making the Confusion Matrix
cm = confusion_matrix(y_Test, y_Pred)
print(cm)

[[   78     1     0     1     0     0]
 [    0 18237     0    16     0     0]
 [    0     0   233    56     7     0]
 [    0     0     0 17236     0     0]
 [    0     0     0   719 14706     0]
 [    0     0     0     0     0     2]]


In [53]:
print(classification_report(y_Test, y_Pred))

              precision    recall  f1-score   support

         BFA       1.00      0.97      0.99        80
        DDoS       1.00      1.00      1.00     18253
         DoS       1.00      0.79      0.88       296
      Normal       0.96      1.00      0.98     17236
       Probe       1.00      0.95      0.98     15425
         U2R       1.00      1.00      1.00         2

    accuracy                           0.98     51292
   macro avg       0.99      0.95      0.97     51292
weighted avg       0.99      0.98      0.98     51292



# DT

In [54]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier

In [58]:
#import the dataset
df = pd.concat(map(pd.read_csv,['metasploitable-2.csv','Normal_data.csv']), ignore_index=True)
df["Src IP"] = [float(str(i).replace(".", "")) for i in df["Src IP"]]
df["Dst IP"] = [float(str(i).replace(".", "")) for i in df["Dst IP"]]
df["Flow ID"] = [float(str(i).replace(".", "").replace("-", "")) for i in df["Flow ID"]]
df["Timestamp"] = [float(str(i).replace("/", "").replace(":", "").replace(" ","").replace("PM","")) for i in df["Timestamp"]]

print(df)

             Flow ID        Src IP  Src Port        Dst IP  Dst Port  \
0       1.921683e+29  1.921683e+09     38694  2.001752e+09      4444   
1       1.921683e+29  1.921683e+09     38693  2.001752e+09      4444   
2       1.921683e+29  2.001752e+09     33747  1.921683e+09      3632   
3       1.921683e+29  2.001752e+09     38745  1.921683e+09      8180   
4       1.921683e+29  2.001752e+09     37217  1.921683e+09      8180   
...              ...           ...       ...           ...       ...   
205162  1.851272e+29  1.921682e+10     36100  1.851272e+09       443   
205163  1.921682e+28  1.921682e+10     53032  1.921682e+08        53   
205164  1.921682e+28  1.921682e+10     39285  1.921682e+08        53   
205165  1.921682e+28  1.921682e+10     49895  1.921682e+08        53   
205166  1.921682e+28  1.921682e+10     33786  1.921682e+08        53   

        Protocol     Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  \
0              6  1.012021e+09         269709             

In [59]:
#here we are preprocessing
X = df.drop('Label', axis =1)
y = df['Label'].values

In [64]:
# Splitting the dataset into the Training set and Test set
X_Train, X_Test, y_Train, y_Test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Stack Model

In [65]:
import numpy as np
import pandas as pd
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report, precision_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

# Example Dataset: Replace this with your dataset
# X, y = df.drop('target', axis=1), df['target']  # Replace 'target' with your actual label column
X = np.random.rand(100, 5)  # Dummy features
y = np.random.randint(0, 2, size=100)  # Dummy binary labels

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define individual models
svm = SVC(probability=True, random_state=0)
nb = GaussianNB()
knn = KNeighborsClassifier()

# Create list of estimators
estimator_list = [
    ('SVM', svm),
    ('NB', nb),
    ('KNN', knn)
]

# Build and fit stack model
stack_model = StackingClassifier(
    estimators=estimator_list, final_estimator=LogisticRegression()
)
stack_model.fit(X_train, y_train)

# Make predictions
y_train_pred = stack_model.predict(X_train)
y_test_pred = stack_model.predict(X_test)

# Training set model performance
train_acc = accuracy_score(y_train, y_train_pred)
train_f1 = f1_score(y_train, y_train_pred, average='weighted')
train_pr = precision_score(y_train, y_train_pred, average='micro')

print('Model performance for Training set:')
print('Accuracy: %s' % train_acc)
print('F1 score: %s' % train_f1)
print('Precision: %s' % train_pr)

# Test set model performance
test_acc = accuracy_score(y_test, y_test_pred)
test_f1 = f1_score(y_test, y_test_pred, average='weighted')
test_pr = precision_score(y_test, y_test_pred, average='micro')

print('\nModel performance for Test set:')
print('Accuracy: %s' % test_acc)
print('F1 score: %s' % test_f1)
print('Precision: %s' % test_pr)

# Confusion Matrix and Classification Report
cm = confusion_matrix(y_test, y_test_pred)
print('\nConfusion Matrix:')
print(cm)

print('\nClassification Report:')
print(classification_report(y_test, y_test_pred))


Model performance for Training set:
Accuracy: 0.6571428571428571
F1 score: 0.6058309037900874
Precision: 0.6571428571428571

Model performance for Test set:
Accuracy: 0.5666666666666667
F1 score: 0.4871202396234489
Precision: 0.5666666666666667

Confusion Matrix:
[[ 3 13]
 [ 0 14]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.19      0.32        16
           1       0.52      1.00      0.68        14

    accuracy                           0.57        30
   macro avg       0.76      0.59      0.50        30
weighted avg       0.78      0.57      0.49        30

